version: '2'

services:
    php-fpm:
        build: ./docker/php-fpm
        ports:
            - 9000:9000
        volumes:
            - ./:/var/www/mycryptool
        links:
            - mysql

    nginx:
        build: ./docker/nginx
        ports:
            - 80:80
        volumes:
            - ./:/var/www/mycryptool
        links:
            - php-fpm

    mysql:
        image: mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: mycryptool
            MYSQL_USER: mycryptool
            MYSQL_PASSWORD: t00l
            MYSQL_ROOT_PASSWORD: t00l123
